### ISSUE TITLE
program_invocation_short_name missing on Mac OS

### ISSUE THREAD

**Issue by dmalan** [cs50/c#14]
Use of `program_invocation_short_name` now causes compilation of the CS50 Library to fail on Mac OS:

```
Undefined symbols for architecture x86_64:
  "_program_invocation_short_name", referenced from:
      _eprintf in cs50.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Seems the variable is missing on Mac OS:
https://www.gnu.org/software/gnulib/manual/html_node/program_005finvocation_005fshort_005fname.html

A recommended fix is:

* https://github.com/hyperion-project/hyperion/issues/693
* https://lists.freedesktop.org/archives/mesa-dev/2013-June/041123.html

```c
#undef GET_PROGRAM_NAME
#ifdef __GLIBC__
#	define GET_PROGRAM_NAME() program_invocation_short_name
#else /* *BSD and OS X */
#	include <stdlib.h>
#	define GET_PROGRAM_NAME() getprogname()
#endif
```

**Comment by liornext** [comment]
We can add `libbsd` as a dependency and just use `getprogname`

https://manpages.debian.org/stretch/libbsd-dev/getprogname.3.en.html
