### ISSUE TITLE
libcs50 clobbers errno

### ISSUE THREAD

**Issue by crossroads1112** [cs50/c#4]
It is generally bad form for a library to change the value of errno without good reason (like reporting an error). `get_long_long`, `get_int`, `get_float`, `get_double` all clobber errno by resetting it to zero before running the relevant  `strto*` function. From a practical perspective, this isn't a big deal since none of the CS50 psets require students to check errno. That said, if students are going to be encouraged to look at the source code, it would seem that it should follow best practices.

The most obvious way to fix this issue would be to add something like `int errno_copy = errno;` before errno is set to zero in each of the aforementioned functions and adding `errno = errno_copy;` after errno is checked. Unfortunately, with how the control flow is branched currently, there isn't a great way to do the latter without duplicating the line. 

The duplication of a single line is not a big deal, however there is a kind of a fun way to avoid it. You could do something like this:

    #define save_errno() __attribute__((cleanup(reset_errno))) int _save_errno = errno
    
    static void reset_errno(int *e)
    {
        errno = *e;
    }

Then before each `errno = 0` line in the afflicted functions, add the line `save_errno()`. For reference, the `cleanup` attribute allows you to specify a function that is run on a value when it goes out of scope.

The simpler solution is probably better but I thought this one was worth mentioning.

**Comment by dmalan** [comment]
Thanks for the thoughtful notes, though not sure the added complexity is necessary. Per `man errno`, it's really the responsibility of a caller to preserve `errno`. Indeed, even "a function that succeeds is allowed to change `errno`." And even more explicitly, "If the value of `errno` should be preserved across a library call, it must be saved."

CC @glennholloway

**Comment by Sebbyastian** [comment]
It might be useful to note that according to the [POSIX manual](http://pubs.opengroup.org/onlinepubs/9699919799/functions/errno.html):

> It is unspecified whether `errno` is a macro or an identifier declared with external linkage.
